apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: freshcart

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
  namespace: freshcart
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: freshcart
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: freshcart
roleRef:
  kind: Role
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io