apiVersion: v1
kind: Secret
metadata:
  name: checkout-api-secrets
  namespace: freshcart
type: Opaque
stringData:
  database-url: postgres://freshcart:freshcart@postgres:5432/freshcart

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: freshcart
type: Opaque
stringData:
  postgres-password: freshcart